apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "another-docs"
  description: "another-docs"
  annotations:
    github.com/project-slug: matiasurrutia/another-docs
    backstage.io/techdocs-ref: url:https://github.com/matiasurrutia/another-docs
spec:
  type: documentation
  lifecycle: experimental
  owner: "MUrrutia"
